# Generated by Django 4.2.23 on 2025-06-28 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_ban_reason_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ban_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the ban expires (null for permanent)', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ban_severity',
            field=models.CharField(blank=True, choices=[('minor', 'Minor (1 day)'), ('moderate', 'Moderate (7 days)'), ('major', 'Major (30 days)'), ('permanent', 'Permanent')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate_content', 'Inappropriate Content'), ('spam', 'Spam'), ('harassment', 'Harassment'), ('fake_listing', 'Fake Listing'), ('scam', 'Scam'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('evidence', models.TextField(blank=True, help_text='Any additional evidence or context', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes on the report', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_user', models.ForeignKey(help_text='User being reported', on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(help_text='User who made the report', on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Admin who resolved this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('reporter', 'reported_user', 'created_at')},
            },
        ),
    ]
