# Generated by Django 4.2.23 on 2025-10-28 08:24

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_ban_expires_at_customuser_ban_severity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_email_ci'),
        ),
    ]
