# Generated by Django 4.2.23 on 2025-12-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='evidence_image',
            field=models.ImageField(blank=True, help_text='Screenshot or image evidence', null=True, upload_to='report_evidence/'),
        ),
    ]
