# Generated by Django 4.2.23 on 2025-12-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userreport_evidence_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='government_id',
            field=models.ImageField(blank=True, null=True, upload_to='verification_docs/government_ids/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_identity_verified',
            field=models.BooleanField(default=False, help_text='Has landlord submitted and been verified?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='proof_of_ownership',
            field=models.ImageField(blank=True, null=True, upload_to='verification_docs/property_ownership/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='selfie_with_id',
            field=models.ImageField(blank=True, null=True, upload_to='verification_docs/selfies/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_status',
            field=models.CharField(choices=[('none', 'Not Requested'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
