# Generated by Django 4.2.23 on 2026-01-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customuser_government_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last time user was active', null=True),
        ),
    ]
