# Generated by Django 4.2.23 on 2026-02-17 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Your age', null=True, validators=[django.core.validators.MinValueValidator(16, message='You must be at least 16 years old'), django.core.validators.MaxValueValidator(100, message='Please enter a valid age')]),
        ),
    ]
