# Generated by Django 4.2.23 on 2025-06-19 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dormitory', '0031_auto_20250613_0031'),
        ('user_profile', '0003_auto_20250619_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('favorite', 'Favorite'), ('book', 'Book')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.dorm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'dorm', 'interaction_type', 'timestamp')},
            },
        ),
    ]
