# Generated by Django 4.2.23 on 2025-11-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
