# Generated by Django 4.2.23 on 2026-01-16 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0005_add_verification_token_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_location', models.CharField(blank=True, help_text='Preferred area/location', max_length=255, null=True)),
                ('max_distance_km', models.FloatField(default=5.0, help_text='Maximum distance from preferred location (in km)')),
                ('min_budget', models.DecimalField(decimal_places=2, default=0, help_text='Minimum budget per month', max_digits=10)),
                ('max_budget', models.DecimalField(decimal_places=2, default=10000, help_text='Maximum budget per month', max_digits=10)),
                ('preferred_gender', models.CharField(choices=[('male', 'Male Only'), ('female', 'Female Only'), ('any', 'No Preference')], default='any', max_length=10)),
                ('preferred_room_type', models.CharField(choices=[('single', 'Single Room'), ('shared', 'Shared Room'), ('any', 'No Preference')], default='any', max_length=10)),
                ('wifi_required', models.BooleanField(default=False)),
                ('parking_required', models.BooleanField(default=False)),
                ('laundry_required', models.BooleanField(default=False)),
                ('kitchen_required', models.BooleanField(default=False)),
                ('aircon_required', models.BooleanField(default=False)),
                ('security_required', models.BooleanField(default=False)),
                ('pet_friendly_required', models.BooleanField(default=False)),
                ('study_area_required', models.BooleanField(default=False)),
                ('near_public_transport', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Preference',
                'verbose_name_plural': 'Tenant Preferences',
            },
        ),
    ]
