# Generated by Django 4.2.23 on 2026-02-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_tenantpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantpreferences',
            name='preferred_roommate_age_range',
            field=models.CharField(choices=[('18-25', '18-25 years'), ('26-35', '26-35 years'), ('36-50', '36-50 years'), ('any', 'No Preference')], default='any', help_text='Preferred roommate age range', max_length=10),
        ),
        migrations.AddField(
            model_name='tenantpreferences',
            name='preferred_roommate_gender',
            field=models.CharField(choices=[('male', 'Male Only'), ('female', 'Female Only'), ('any', 'No Preference')], default='any', help_text='Preferred roommate gender', max_length=10),
        ),
        migrations.AddField(
            model_name='tenantpreferences',
            name='preferred_roommate_mood',
            field=models.CharField(choices=[('quiet', 'Quiet and Reserved'), ('friendly', 'Friendly and Social'), ('adventurous', 'Adventurous and Outgoing'), ('studious', 'Studious and Focused'), ('any', 'No Preference')], default='any', help_text='Preferred roommate personality type', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantpreferences',
            name='roommate_budget_max',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Maximum budget for roommate search (optional)', max_digits=10),
        ),
        migrations.AddField(
            model_name='tenantpreferences',
            name='roommate_budget_min',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum budget for roommate search (optional)', max_digits=10),
        ),
        migrations.AddField(
            model_name='tenantpreferences',
            name='roommate_cleanliness_important',
            field=models.BooleanField(default=False, help_text='Is cleanliness important to you?'),
        ),
        migrations.AddField(
            model_name='tenantpreferences',
            name='roommate_preferred_location',
            field=models.CharField(blank=True, help_text='Preferred location for roommate search', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantpreferences',
            name='roommate_quiet_environment',
            field=models.BooleanField(default=False, help_text='Do you prefer a quiet environment?'),
        ),
        migrations.AddField(
            model_name='tenantpreferences',
            name='roommate_shared_expenses',
            field=models.BooleanField(default=False, help_text='Open to sharing household expenses?'),
        ),
        migrations.AddField(
            model_name='tenantpreferences',
            name='roommate_social_activities',
            field=models.BooleanField(default=False, help_text='Do you enjoy social activities with roommates?'),
        ),
    ]
