# Generated by Django 4.2.23 on 2026-02-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_tenantpreferences_preferred_roommate_age_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantpreferences',
            name='preference_choice',
            field=models.CharField(choices=[('dorm_only', 'Find Dorm Only'), ('dorm_and_roommate', 'Find Dorm and Roommate')], default='dorm_only', help_text='Whether user wants to find just dorm or dorm + roommate', max_length=20),
        ),
    ]
