# Generated by Copilot on 2026-04-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_tenantpreferences_preference_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_pwd_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pwd_document',
            field=models.ImageField(blank=True, null=True, upload_to='verification_docs/pwd/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pwd_discount_percent',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pwd_reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pwd_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pwd_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pwd_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pwd_verification_status',
            field=models.CharField(choices=[('none', 'Not Submitted'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
    ]
