# Generated by Django 4.2.23 on 2026-06-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_tenantpreferences_others_and_personalities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantpreferences',
            name='preferred_room_type',
            field=models.CharField(choices=[('whole_unit', 'Whole Unit'), ('bedspace', 'Bed Space / Shared Space'), ('single', 'Single Room'), ('shared', 'Shared Room'), ('any', 'No Preference')], default='any', max_length=10),
        ),
    ]
