# Generated by Django 5.1.5 on 2025-03-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0002_dorm_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
