# Generated by Django 3.2 on 2025-03-09 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0003_dorm_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dorm',
            name='image',
        ),
        migrations.AddField(
            model_name='dorm',
            name='permit',
            field=models.FileField(blank=True, null=True, upload_to='dorm_permits/'),
        ),
        migrations.CreateModel(
            name='DormImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dorm_images/')),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dormitory.dorm')),
            ],
        ),
    ]
