# Generated by Django 3.2 on 2025-03-13 06:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dormitory', '0005_auto_20250309_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Roommate Amenities',
            },
        ),
        migrations.CreateModel(
            name='RoommatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(help_text='Provide a contact number for potential roommates.', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid contact number.', regex='^\\+?\\d{9,15}$')])),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('mood', models.CharField(choices=[('quiet', 'Quiet'), ('friendly', 'Friendly'), ('adventurous', 'Adventurous'), ('studious', 'Studious')], db_index=True, default='friendly', max_length=20)),
                ('preferred_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('preferred_location', models.CharField(db_index=True, help_text='Where do you want to stay? (e.g., near UST, UP Diliman)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Describe your ideal roommate and preferences.')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='roommate_posts', to='dormitory.RoommateAmenity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
