# Generated by Django 3.2 on 2025-03-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0007_roommatepost_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommatepost',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='roommate_profiles/'),
        ),
    ]
