# Generated by Django 3.2 on 2025-05-28 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0013_auto_20250528_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dorm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='dormitory.dorm'),
        ),
    ]
