# Generated by Django 3.2 on 2025-05-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0014_auto_20250528_1814'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservation',
            table='dormitory_reservation',
        ),
    ]
