# Generated by Django 3.2 on 2025-05-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0016_auto_20250528_1854'),
    ]

    operations = [
        migrations.RunSQL(
            # Drop existing tables if they exist
            """
            DROP TABLE IF EXISTS dormitory_reservation_message;
            """,
            reverse_sql="""
            CREATE TABLE IF NOT EXISTS dormitory_reservation_message (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                content TEXT NOT NULL,
                timestamp DATETIME NOT NULL,
                is_read BOOLEAN NOT NULL,
                reservation_id INTEGER NOT NULL REFERENCES dormitory_reservation(id),
                sender_id INTEGER NOT NULL REFERENCES accounts_customuser(id)
            );
            """
        ),
    ]
