# Generated by Django 3.2 on 2025-05-28 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0019_auto_20250528_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='dormitory.reservation'),
        ),
    ]
