# Generated by Django 3.2 on 2025-05-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0020_review_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='payment_qr',
            field=models.ImageField(blank=True, help_text='Upload your GCash/Maya QR code for payments', null=True, upload_to='payment_qr_codes/'),
        ),
    ]
