# Generated by Django 3.2 on 2025-05-29 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0021_dorm_payment_qr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roommatepost',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Roommate Listing', 'verbose_name_plural': 'Roommate Listings'},
        ),
        migrations.AddField(
            model_name='roommatepost',
            name='preferred_budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Maximum monthly budget (in PHP)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='roommatepost',
            name='preferred_budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Minimum monthly budget (in PHP)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='roommatepost',
            name='age',
            field=models.PositiveIntegerField(default=18, help_text='Your age (must be between 16 and 100)', validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='roommatepost',
            name='amenities',
            field=models.ManyToManyField(blank=True, help_text='Select your preferred amenities', related_name='roommate_posts', to='dormitory.RoommateAmenity'),
        ),
        migrations.AlterField(
            model_name='roommatepost',
            name='contact_number',
            field=models.CharField(help_text='Your Philippine mobile number (e.g., 9123456789)', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid Philippine mobile number starting with 9 (e.g., 9123456789)', regex='^9\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='roommatepost',
            name='description',
            field=models.TextField(blank=True, help_text="Describe yourself and what you're looking for in a roommate"),
        ),
        migrations.AlterField(
            model_name='roommatepost',
            name='hobbies',
            field=models.TextField(blank=True, help_text='List your hobbies and interests', null=True),
        ),
        migrations.AlterField(
            model_name='roommatepost',
            name='mood',
            field=models.CharField(choices=[('quiet', 'Quiet and Reserved'), ('friendly', 'Friendly and Social'), ('adventurous', 'Adventurous and Outgoing'), ('studious', 'Studious and Focused')], db_index=True, default='friendly', help_text='Choose the personality type that best describes you', max_length=20),
        ),
        migrations.AlterField(
            model_name='roommatepost',
            name='name',
            field=models.CharField(help_text='Your full name', max_length=255),
        ),
        migrations.AlterField(
            model_name='roommatepost',
            name='preferred_budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, help_text='Average monthly budget (automatically calculated)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='roommatepost',
            name='preferred_location',
            field=models.CharField(db_index=True, help_text='Where do you want to stay? (e.g., España, Manila near UST)', max_length=255),
        ),
        migrations.AlterField(
            model_name='roommatepost',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (optional)', null=True, upload_to='roommate_profiles/'),
        ),
    ]
