# Generated by Django 3.2 on 2025-06-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0023_update_roommate_budgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='accommodation_type',
            field=models.CharField(choices=[('whole_unit', 'Whole Unit'), ('bedspace', 'Bed Space'), ('room_sharing', 'Room Sharing')], default='whole_unit', max_length=20),
        ),
        migrations.AddField(
            model_name='dorm',
            name='available_beds',
            field=models.PositiveIntegerField(default=1, help_text='Number of beds currently available'),
        ),
        migrations.AddField(
            model_name='dorm',
            name='is_aircon',
            field=models.BooleanField(default=False, help_text='Does the room have air conditioning?'),
        ),
        migrations.AddField(
            model_name='dorm',
            name='max_occupants',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of occupants allowed'),
        ),
        migrations.AddField(
            model_name='dorm',
            name='total_beds',
            field=models.PositiveIntegerField(default=1, help_text='Total number of beds available (for bedspace/room sharing)'),
        ),
        migrations.AddField(
            model_name='dorm',
            name='utilities_included',
            field=models.BooleanField(default=False, help_text='Are utilities (electricity, water) included in the price?'),
        ),
    ]
