# Generated by Django 3.2 on 2025-06-03 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dormitory', '0026_roommatechat_roommatematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommatechat',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_roommate_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
