# Generated by Django 3.2 on 2025-06-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0027_roommatechat_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='recent_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
