# Generated by Django 3.2 on 2025-06-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0029_auto_20250604_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation if the reservation was cancelled', null=True),
        ),
    ]
