# Generated by Django 3.2 on 2025-06-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0030_reservation_cancellation_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dorm',
            name='is_aircon',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='utilities_included',
        ),
    ]
