# Generated by Django 4.2.23 on 2025-06-22 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0031_auto_20250613_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
