# Generated by Django 4.2.23 on 2025-07-13 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0032_dorm_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or label for this room (e.g., Room 1, Bed A)', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Monthly price for this room', max_digits=10)),
                ('is_available', models.BooleanField(default=True, help_text='Is this room currently available?')),
                ('description', models.TextField(blank=True, help_text='Optional description for this room', null=True)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='dormitory.dorm')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dormitory.room')),
            ],
        ),
    ]
