# Generated by Django 4.2.23 on 2025-10-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0034_reservation_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Number of people this room can accommodate'),
        ),
        migrations.AddField(
            model_name='room',
            name='floor_number',
            field=models.PositiveIntegerField(blank=True, help_text='Floor where the room is located', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('shared', 'Shared')], default='single', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size in square meters', max_digits=6, null=True),
        ),
    ]
