# Generated by Django 4.2.23 on 2025-10-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0035_room_capacity_room_floor_number_room_room_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='key_features',
            field=models.TextField(blank=True, help_text='Short highlights, one per line', null=True),
        ),
    ]
