# Generated by Django 4.2.23 on 2025-11-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0036_dorm_key_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='payment_terms',
            field=models.TextField(blank=True, help_text="Payment terms (e.g., '3 months deposit, 1 month advance')", null=True),
        ),
    ]
