# Generated by Django 4.2.23 on 2025-12-12 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dormitory', '0038_roommatechatreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_payment_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for payment (48 hours from reservation)', null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('pending_payment', 'Awaiting Payment'), ('confirmed', 'Confirmed'), ('completed', 'Transaction Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DormVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('09:00-11:00', '9:00 AM - 11:00 AM'), ('11:00-13:00', '11:00 AM - 1:00 PM'), ('13:00-15:00', '1:00 PM - 3:00 PM'), ('15:00-17:00', '3:00 PM - 5:00 PM'), ('17:00-19:00', '5:00 PM - 7:00 PM')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Landlord Confirmation'), ('confirmed', 'Visit Confirmed'), ('completed', 'Visit Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined by Landlord'), ('no_show', 'Student Did Not Show Up')], default='pending', max_length=20)),
                ('student_message', models.TextField(blank=True, help_text='Message from student to landlord', null=True)),
                ('landlord_notes', models.TextField(blank=True, help_text='Internal notes from landlord', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='dormitory.dorm')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='dorm_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dormitory_visit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='visit',
            field=models.OneToOneField(blank=True, help_text='The visit that led to this reservation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='dormitory.dormvisit'),
        ),
    ]
