# Generated by Django 4.2.23 on 2025-12-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0039_reservation_is_payment_overdue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checklist_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checklist_inventory_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checklist_keys_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checklist_property_inspected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checklist_rules_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='move_in_date',
            field=models.DateField(blank=True, help_text='Scheduled move-in date', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='move_in_notes',
            field=models.TextField(blank=True, help_text='Move-in instructions from landlord'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='visit_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='visit_date',
            field=models.DateField(blank=True, help_text='Scheduled visit date', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='visit_notes',
            field=models.TextField(blank=True, help_text='Landlord notes about the visit'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='visit_scheduled',
            field=models.BooleanField(default=False, help_text='Whether landlord scheduled a visit'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='visit_status',
            field=models.CharField(choices=[('not_scheduled', 'Not Scheduled'), ('scheduled', 'Visit Scheduled'), ('completed', 'Visit Completed'), ('cancelled', 'Visit Cancelled')], default='not_scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='visit_time_slot',
            field=models.CharField(blank=True, choices=[('09:00-11:00', '9:00 AM - 11:00 AM'), ('11:00-13:00', '11:00 AM - 1:00 PM'), ('13:00-15:00', '1:00 PM - 3:00 PM'), ('15:00-17:00', '3:00 PM - 5:00 PM'), ('17:00-19:00', '5:00 PM - 7:00 PM')], max_length=20, null=True),
        ),
    ]
