# Generated by Django 4.2.23 on 2025-12-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0040_reservation_checklist_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('pending_payment', 'Awaiting Payment'), ('confirmed', 'Confirmed'), ('occupied', 'Tenant Checked In'), ('completed', 'Tenant Moved Out'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
