# Generated by Django 4.2.23 on 2025-12-12 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dormitory', '0041_add_occupied_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('reservation_created', 'Reservation Created'), ('reservation_confirmed', 'Reservation Confirmed'), ('reservation_cancelled', 'Reservation Cancelled'), ('payment_received', 'Payment Received'), ('payment_verified', 'Payment Verified'), ('payment_rejected', 'Payment Rejected'), ('visit_scheduled', 'Visit Scheduled'), ('visit_completed', 'Visit Completed'), ('visit_cancelled', 'Visit Cancelled'), ('tenant_moved_in', 'Tenant Checked In'), ('tenant_moved_out', 'Tenant Moved Out'), ('review_received', 'Review Received'), ('dorm_created', 'Dorm Listed'), ('dorm_updated', 'Dorm Updated'), ('message_received', 'Message Received')], max_length=30)),
                ('status', models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='success', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Transaction amount if applicable', max_digits=10, null=True)),
                ('description', models.TextField(help_text='Description of the transaction')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction details')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('dorm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to='dormitory.dorm')),
                ('landlord', models.ForeignKey(limit_choices_to={'user_type': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to='dormitory.reservation')),
                ('tenant', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'tenant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_transaction_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['landlord', '-created_at'], name='dormitory_t_landlor_6b6a69_idx'), models.Index(fields=['transaction_type', '-created_at'], name='dormitory_t_transac_9d6ed7_idx'), models.Index(fields=['dorm', '-created_at'], name='dormitory_t_dorm_id_905990_idx')],
            },
        ),
    ]
