# Generated by Django 4.2.23 on 2026-01-22 08:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0042_transactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='Payment gateway transaction ID (e.g., MonGo Pay)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('gateway', 'Payment Gateway'), ('manual', 'Manual Upload'), ('cash', 'Cash Payment')], default='manual', help_text='Method used for payment', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Current status of the payment', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the payment was verified by gateway or landlord', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount refunded to tenant', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_reason',
            field=models.TextField(blank=True, help_text='Reason for refund if applicable', null=True),
        ),
        migrations.CreateModel(
            name='PaymentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_months', models.IntegerField(default=2, help_text='Number of months for security deposit (e.g., 2 months)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('advance_months', models.IntegerField(default=1, help_text='Number of months for advance payment (e.g., 1 month)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('processing_fee_percent', models.DecimalField(decimal_places=2, default=2.5, help_text='Processing fee percentage (e.g., 2.5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('accepts_partial_payment', models.BooleanField(default=False, help_text='Allow tenants to pay in installments')),
                ('partial_payment_percent', models.DecimalField(decimal_places=2, default=50.0, help_text='Percentage required for first installment', max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('accepts_gateway', models.BooleanField(default=True, help_text='Accept online payment gateway')),
                ('accepts_manual', models.BooleanField(default=True, help_text='Accept manual payment upload')),
                ('accepts_cash', models.BooleanField(default=False, help_text='Accept cash payment on-site')),
                ('refund_before_days', models.IntegerField(default=7, help_text='Full refund if cancelled X days before move-in', validators=[django.core.validators.MinValueValidator(0)])),
                ('partial_refund_percent', models.DecimalField(decimal_places=2, default=50.0, help_text='Partial refund percentage if cancelled late', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dorm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_config', to='dormitory.dorm')),
            ],
            options={
                'verbose_name': 'Payment Configuration',
                'verbose_name_plural': 'Payment Configurations',
            },
        ),
    ]
