# Generated by Django 4.2.23 on 2026-01-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0044_chatbotconversation_chatbotfaq_chatbotmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommatechat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='roommatechat',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
