# Generated by Django 4.2.23 on 2026-01-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0045_roommatechat_image_alter_roommatechat_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommatechat',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roommatematch',
            name='compatibility_factors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='roommatematch',
            name='user_feedback_score',
            field=models.IntegerField(blank=True, help_text='User rating of match quality (1-5)', null=True),
        ),
    ]
