# Generated by Django 4.2.23 on 2026-02-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0046_roommatechat_read_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='transaction_type',
            field=models.CharField(choices=[('reservation_created', 'Reservation Created'), ('reservation_confirmed', 'Reservation Confirmed'), ('reservation_cancelled', 'Reservation Cancelled'), ('payment_received', 'Payment Received'), ('payment_verified', 'Payment Verified'), ('payment_rejected', 'Payment Rejected'), ('visit_scheduled', 'Visit Scheduled'), ('visit_completed', 'Visit Completed'), ('visit_cancelled', 'Visit Cancelled'), ('tenant_moved_in', 'Tenant Moved In'), ('tenant_moved_out', 'Tenant Moved Out'), ('review_received', 'Review Received'), ('dorm_created', 'Dorm Listed'), ('dorm_updated', 'Dorm Updated'), ('dorm_approved', 'Dorm Approved'), ('dorm_rejected', 'Dorm Rejected'), ('message_received', 'Message Received'), ('inquiry_received', 'Inquiry Received')], max_length=30),
        ),
    ]
