# Generated by Django 4.2.23 on 2026-03-16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dormitory', '0047_alter_transactionlog_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mongopay', 'MonGo Pay'), ('paymongo', 'PayMongo')], max_length=20)),
                ('event_type', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('failed', 'Failed')], default='info', max_length=20)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('external_event_id', models.CharField(blank=True, max_length=120)),
                ('payment_intent_id', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('dorm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='dormitory.dorm')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='dormitory.reservation')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['provider', 'event_type', '-created_at'], name='payevt_prov_evt_created_idx'),
                    models.Index(fields=['reservation', '-created_at'], name='payevt_reservation_created_idx'),
                    models.Index(fields=['correlation_id', '-created_at'], name='payevt_corr_created_idx'),
                ],
            },
        ),
    ]
