# Generated by Django 4.2.23 on 2026-03-16 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0048_paymenteventlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymenteventlog',
            new_name='dormitory_p_provide_4c6739_idx',
            old_name='payevt_prov_evt_created_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenteventlog',
            new_name='dormitory_p_reserva_1e9721_idx',
            old_name='payevt_reservation_created_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenteventlog',
            new_name='dormitory_p_correla_f69f4d_idx',
            old_name='payevt_corr_created_idx',
        ),
    ]
