# Generated by Django 4.2.23 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0049_rename_payevt_prov_evt_created_idx_dormitory_p_provide_4c6739_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('gateway', 'Payment Gateway'),
                    ('gcash', 'GCash (PayMongo Source)'),
                    ('paymongo_checkout', 'PayMongo Checkout Session'),
                    ('manual', 'Manual Upload'),
                    ('cash', 'Cash Payment'),
                ],
                default='manual',
                help_text='Method used for payment',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('processing', 'Processing'),
                    ('success', 'Success'),
                    ('paid', 'Paid (Legacy)'),
                    ('failed', 'Failed'),
                    ('refunded', 'Refunded'),
                ],
                default='pending',
                help_text='Current status of the payment',
                max_length=20,
            ),
        ),
    ]
