# Generated by Django 4.2.23 on 2026-04-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0050_alter_reservation_payment_method_and_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='manual_ocr_raw_text',
            field=models.TextField(blank=True, default='', help_text='Raw OCR text extracted from manual payment proof'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='manual_reference_number',
            field=models.CharField(blank=True, help_text='Reference number extracted from manual payment proof OCR', max_length=80, null=True),
        ),
    ]
