# Generated by Django 4.2.23 on 2026-04-19 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0051_reservation_manual_ocr_raw_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormAmenityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dorm_amenity_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dorm_images', to='dormitory.amenity')),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_images', to='dormitory.dorm')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dormamenityimage',
            constraint=models.UniqueConstraint(fields=('dorm', 'amenity'), name='unique_dorm_amenity_image'),
        ),
    ]
