# Generated by Django 4.2.23 on 2026-06-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0055_reservation_reschedule_request_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommatepost',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Controls whether this roommate profile is visible to other users'),
        ),
        migrations.AlterField(
            model_name='dormvisit',
            name='time_slot',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('flexible', 'Flexible / To Be Finalized')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='tenant_preferred_visit_window',
            field=models.CharField(blank=True, choices=[('09:00-11:00', '9:00 AM - 11:00 AM'), ('11:00-13:00', '11:00 AM - 1:00 PM'), ('13:00-15:00', '1:00 PM - 3:00 PM'), ('15:00-17:00', '3:00 PM - 5:00 PM'), ('17:00-19:00', '5:00 PM - 7:00 PM')], help_text='Tenant preferred generalized visit window when requesting reschedule', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='visit_time_slot',
            field=models.CharField(blank=True, choices=[('09:00-11:00', '9:00 AM - 11:00 AM'), ('11:00-13:00', '11:00 AM - 1:00 PM'), ('13:00-15:00', '1:00 PM - 3:00 PM'), ('15:00-17:00', '3:00 PM - 5:00 PM'), ('17:00-19:00', '5:00 PM - 7:00 PM')], max_length=20, null=True),
        ),
    ]
