# Generated by Django 4.2.23 on 2026-06-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0056_roommatepost_is_public_alter_dormvisit_time_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='other_amenities',
            field=models.TextField(blank=True, default='', help_text='List any amenities that are not available in the standard amenity list'),
        ),
    ]
