# Generated by Django 4.2.23 on 2026-06-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0057_dorm_other_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='move_out_approved',
            field=models.BooleanField(default=False, help_text='Whether landlord approved the move-out request'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='move_out_approved_date',
            field=models.DateTimeField(blank=True, help_text='When landlord approved move-out', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='move_out_requested',
            field=models.BooleanField(default=False, help_text='Whether tenant has requested early move-out'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='move_out_requested_date',
            field=models.DateTimeField(blank=True, help_text='When the tenant requested move-out', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='move_out_requested_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for move-out request'),
        ),
    ]
