# Generated by Django 4.2.23 on 2026-06-15 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dormitory', '0058_reservation_move_out_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.OneToOneField(limit_choices_to={'user_type': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='terms_and_conditions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Landlord Terms and Conditions',
            },
        ),
    ]
