# Generated by Django 4.2.23 on 2026-06-26 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dormitory', '0059_landlordterms'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyOutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('financial', 'Financial problems'), ('found_dorm', 'Found another dorm'), ('transfer_school', 'Transferring school'), ('family_emergency', 'Family emergency'), ('personal', 'Personal reasons'), ('other', 'Other (please specify)')], max_length=20)),
                ('reason_other_text', models.TextField(blank=True, default='')),
                ('requested_moveout_date', models.DateField()),
                ('additional_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('landlord_decline_reason', models.CharField(blank=True, choices=[('minimum_stay', 'Minimum stay requirement not met (6 months required)'), ('active_lease', 'Active lease agreement still in effect'), ('unpaid_balance', 'Unpaid balance exists on your account'), ('security_deposit', 'Early termination — security deposit will be forfeited'), ('notice_period', 'Required 30-day notice period not met'), ('incomplete_requirements', 'Incomplete clearance requirements'), ('other', 'Other (please specify)')], default='', max_length=30)),
                ('landlord_decline_other_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_out_requests', to='dormitory.reservation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_out_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
